# Generated by Django 3.0.4 on 2020-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('image_url', models.URLField(blank=True)),
                ('credit_card', models.SmallIntegerField(blank=True)),
            ],
        ),
    ]
