# Generated by Django 3.0.4 on 2020-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_amazon', '0005_auto_20200424_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
